version: '3'

services:
  
  dispenser-backend:
    image: vivaconagua/dispenser-backend:latest
    build: .
    container_name: dispenser-backend
    restart: unless-stopped

  dispenser-db:
     image: mariadb
     container_name: drops-database
     environment: 
      - MYSQL_DATABASE=drops 
      - MYSQL_USER=drops
      - MYSQL_PASSWORD=drops 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
